#!/bin/bash
# Script for compiling versions for released compilers.
../compilers/jalv24q6-i686 18f14k50_blink_hs.jal
mv 18f14k50_blink_hs.hex 18f14k50_blink_hs_jalv24q6_linux_32.hex
../compilers/jalv24q6-x86-64 18f14k50_blink_hs.jal
mv 18f14k50_blink_hs.hex 18f14k50_blink_hs_jalv24q6_linux_64.hex
../compilers/jalv25-i686 18f14k50_blink_hs.jal
mv 18f14k50_blink_hs.hex 18f14k50_blink_hs_jalv25_linux_32.hex
../compilers/jalv25-x86-64 18f14k50_blink_hs.jal
mv 18f14k50_blink_hs.hex 18f14k50_blink_hs_jalv25_linux_64.hex
rm *.asm
rm *.cod

