#!/bin/bash
# Script for compiling versions for released compilers.
# Note: jalv24q6 does not support more than 32 banks (pragma numbanks)
../compilers/jalv25-i686 16f18446_blink_hs.jal
mv 16f18446_blink_hs.hex 16f18446_blink_hs_jalv25_linux_32.hex
../compilers/jalv25-x86-64 16f18446_blink_hs.jal
mv 16f18446_blink_hs.hex 16f18446_blink_hs_jalv25_linux_64.hex
rm *.asm
rm *.cod

