name: 'Linux Compile 32-bit'

# Compile the JAL compiler for Linux 32-bit and save the produced executable
# Author: Rob Jansen, copyright (c) 2023..2023, all rights reserverd

on: workflow_dispatch

jobs:
  runscript:
    name: runscript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build for Linux
        run: |
          cd ${{ github.workspace }}/src/jal
          chmod +x build.sh
          cd ${{ github.workspace }}/src
          bash ${{ github.workspace }}/src/make_32

      - name: Upload binaries to release
        uses: actions/upload-artifact@v3
        with: 
          name: jalv2-i686
          path: ${{ github.workspace }}/bin/jalv2-i686
  
 
