name: 'Linux Compile 64-bit'

# Compile the JAL compiler for Linux 64-bit and save the produced executable
# Author: Rob Jansen, copyright (c) 2023..2023, all rights reserverd

on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v3
       - name: Build for Linux
         run:
           cd  ${{ github.workspace }}/src
           bash make_64

       - name: Upload binaries to release
         uses: actions/upload-artifact@v3
         with: 
           name: jalv2
           path: ${{ github.workspace }}/bin
  
 
