name: 'Windows Compile 64-bit'

# Compile the JAL 64-bit compiler for Windows save the produced executable
# Author: Rob Jansen, copyright (c) 2023..2023, all rights reserverd

on: workflow_dispatch

jobs:
  runscript:
    name: Run batchfile
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build for Windows
        shell: cmd
        run: |
           cd  ${{ github.workspace }}\src
           cmd /c "make_64_github.bat"

      - name: Upload binaries to release
        uses: actions/upload-artifact@v3
        with: 
          name: jalv2_64.exe
          path: ${{ github.workspace }}\bin\jalv2_64.exe
          
          
