name: 'Windows Compile 32-bit'

# Compile the JAL 32-bit compiler for Windows save the produced executable
# Author: Rob Jansen, copyright (c) 2023..2023, all rights reserverd

on: workflow_dispatch
jobs:
   example_matrix:
     runs-on: windows-2019
     strategy:
       matrix:
         os-version: [ windows-2019 ]
         compiler: [ gcc-latest ]
     steps:
       - uses: actions/checkout@v3
       - name: Build for Windows
         shell: cmd
         run:
           echo ${{ github.workspace }}
           cd  ${{ github.workspace }}\src
           cmd /c "make_32.bat"

       - name: Upload binary
         uses: actions/upload-artifact@v3
         with: 
           name: jalv2.exe
           path: ${{ github.workspace }}\bin\jalv2
  
